# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='date_drafted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
