# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_mypost_date_drafted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypost',
            name='date_created',
        ),
        migrations.AddField(
            model_name='mypost',
            name='date_unpublished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='date_drafted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
