# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161205_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
