# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_mypost_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/'),
        ),
    ]
