# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_mypost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='/media/files'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='/media/images/'),
        ),
    ]
