# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20161206_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='/media/files/'),
        ),
    ]
