# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20161206_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=250)),
                ('comment_text', models.TextField()),
                ('comment_date_drafted', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_date_approved', models.DateTimeField(blank=True, null=True)),
                ('comment_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='mypost',
            name='is_archieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='my_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.MyPost'),
        ),
    ]
