# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20161213_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_date_approved',
            new_name='date_approved',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_date_drafted',
            new_name='date_drafted',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='text',
        ),
    ]
