# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20161213_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypost',
            name='is_archieved',
        ),
    ]
