# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_mypost_is_archieved'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('dated_drafted', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='mypost',
            name='date_archived',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mycomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.MyPost'),
        ),
    ]
