# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20161213_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycomment',
            old_name='dated_drafted',
            new_name='date_drafted',
        ),
    ]
